/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/campaign` | `/campaign`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coupons` | `/coupons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/game` | `/game`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/merchant` | `/merchant`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mode-libre` | `/mode-libre`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/multiplayer` | `/multiplayer`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/campaign` | `/campaign`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/coupons` | `/coupons`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/game` | `/game`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/merchant` | `/merchant`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mode-libre` | `/mode-libre`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/multiplayer` | `/multiplayer`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/campaign${`?${string}` | `#${string}` | ''}` | `/campaign${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/coupons${`?${string}` | `#${string}` | ''}` | `/coupons${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/game${`?${string}` | `#${string}` | ''}` | `/game${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/merchant${`?${string}` | `#${string}` | ''}` | `/merchant${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mode-libre${`?${string}` | `#${string}` | ''}` | `/mode-libre${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/multiplayer${`?${string}` | `#${string}` | ''}` | `/multiplayer${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/campaign` | `/campaign`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coupons` | `/coupons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/game` | `/game`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/merchant` | `/merchant`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mode-libre` | `/mode-libre`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/multiplayer` | `/multiplayer`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
